language: c
sudo: true

addons:
   apt:
      packages:
         - gfortran
         - libblas-dev 
         - liblapack-dev 

install:
   - cd soc
   - cp Makefile.gfortran_travis Makefile
   - make 
   - cd ..

script:
   - cd examples
   - sh run_test_Bi2Se3.sh
   - cd ../soc

after_success:
   - bash <(curl -s https://codecov.io/bash)

fixes:
     - "build/::soc/"
