language: c
sudo: true

addons:
   apt:
      packages:
         - gfortran
         - libblas-dev 
         - liblapack-dev 

install:
   - cd soc
   - cp Makefile.gfortran Makefile
   - make 
   - cd ..

script:
   - cd examples
   - sh run_test_Bi2Se3.sh
